package minion;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

	public static void main(String[] args) {
		Library library = new Library();
		System.out.println(library.someLibraryMethod());
	}

    public boolean someLibraryMethod() {
        return true;
    }
}
